import { GroupBox, TabWidget, VerticalBox, HorizontalBox, Button, LineEdit, GridBox, ListView, StandardTableView, CheckBox } from "std-widgets.slint";

export component Fark inherits Window {
    title: "Fark";
    width: 600px;
    height: 500px;
    callback show-open-dialog;
    callback search;
    callback stop_search;
    callback current-row-changed(int);

    in property file_name <=> file_name.text;
    in property path <=> path.text;
    in property<[[StandardListViewItem]]> rows: [];
    in-out property current-row <=> list.current-row;
    in-out property <bool> started: false;
    in-out property glob <=> glob.checked;
    in-out property case <=> case.checked;

    GroupBox {
        preferred_width: 600px;
        preferred_height: 500px;
        TabWidget {
            Tab {
                title: @tr("Name/Location");
                GridBox {
                    Row {
                        HorizontalBox {
                            Text {
                                vertical-alignment: center;
                                horizontal-alignment: left;
                                text: @tr("File Name:");
                                width: 15%;
                            }
                            
                            file_name := LineEdit {
                                width: 75%;
                            }
                        }
                    }

                    Row {
                        HorizontalBox {
                            Text {
                                vertical-alignment: center;
                                horizontal-alignment: left;
                                text: @tr("Location:");
                                width: 15%;
                            }
                            path := LineEdit {
                                width: 60%;
                                
                            }
                            open_button := Button {
                                text: @tr("Browse...");
                                clicked => { root.show-open-dialog(); }
                                width: 15%;
                            }
                        }
                    }

                    Row {
                        HorizontalBox {
                            spacing: 30px;
                            alignment: center;
                            search := Button {
                                text: root.started ? @tr("Stop") : @tr("Search");
                                clicked => {
                                    if (!root.started) {
                                        root.started = true;
                                        root.search();
                                    } else {
                                        root.stop-search();
                                    }
                                }
                                width: 20%;
                            }
                            glob := CheckBox {
                                text: @tr("Glob");
                            }
                            case := CheckBox {
                                text: @tr("Case sensitive");
                            }
                        }
                    }

                    Row {
                        list := StandardTableView {
                            width: 90%;
                            height: 60%;
                            columns: [
                                // { title: "Name" },
                                // { title: "Type" },
                                { title: "Path" },
                            ];
                            rows: root.rows;
                            current-row-changed(int) => { current-row-changed(int); }
                        }
                    }
                }
            }
        }
    }
}